// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/focalboard/boards/single": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get a single board by its ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board Id",
                        "name": "boardId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "error code, e.g. \"invalid_parameter\"",
                    "type": "string"
                },
                "detail": {
                    "description": "detailed error information",
                    "type": "string"
                },
                "message": {
                    "description": "user-friendly error message",
                    "type": "string"
                },
                "params": {
                    "description": "additional parameters",
                    "type": "object",
                    "additionalProperties": true
                },
                "system_id": {
                    "description": "system identifier",
                    "type": "string"
                },
                "type": {
                    "description": "error type: business_error or system_error",
                    "allOf": [
                        {
                            "$ref": "#/definitions/errors.ErrorType"
                        }
                    ]
                }
            }
        },
        "errors.ErrorType": {
            "type": "string",
            "enum": [
                "business_error",
                "system_error"
            ],
            "x-enum-varnames": [
                "ErrorTypeBusiness",
                "ErrorTypeSystem"
            ]
        },
        "middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/errors.AppError"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
