definitions:
  errors.AppError:
    properties:
      code:
        description: error code, e.g. "invalid_parameter"
        type: string
      detail:
        description: detailed error information
        type: string
      message:
        description: user-friendly error message
        type: string
      params:
        additionalProperties: true
        description: additional parameters
        type: object
      system_id:
        description: system identifier
        type: string
      type:
        allOf:
        - $ref: '#/definitions/errors.ErrorType'
        description: 'error type: business_error or system_error'
    type: object
  errors.ErrorType:
    enum:
    - business_error
    - system_error
    type: string
    x-enum-varnames:
    - ErrorTypeBusiness
    - ErrorTypeSystem
  middleware.ErrorResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/errors.AppError'
      success:
        type: boolean
    type: object
  middleware.SuccessResponse:
    properties:
      data: {}
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/focalboard/boards/single:
    get:
      parameters:
      - description: Board Id
        in: query
        name: boardId
        required: true
        type: string
      - description: User token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/middleware.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.ErrorResponse'
      summary: Get a single board by its ID.
swagger: "2.0"
